sale_quotation_number: Migration to v10.0
versada/sale-workflow pull request #2
Opened 2017-02-07 16:39 UTC by DarkoNikolovski

2017-02-08 08:53 UTC, paulius-sladkevicius requested changes

2017-02-08 08:53 UTC, paulius-sladkevicius commented on sale_quotation_number/model/sale_order.py
> +                'origin': quo,
I suggest to put sale.name here instead creating quo.

2017-02-09 13:58 UTC, DarkoNikolovski commented
Since there is no any additional notes for this PR I will create PR to OCA and will deploy it to the dev server for testing

2017-05-03 07:09 UTC, kkarolis commented
@DarkoNikolovski is this still active, maybe we can close it?

2017-05-03 11:37 UTC, DarkoNikolovski commented
I was waiting for merging on OCA before this to be merged. I can see only one suggestion there, will update the code and after that will merge it and close.

2018-11-11 15:22 UTC, paulius-sladkevicius commented
@DarkoNikolovski, please check if it's still relevant, otherwise close.

2020-05-11 13:32 UTC, closed without merging